(ns ludovico.core
  (:require
    [cljs.core.match :refer-macros [match]]
    [dommy.core :refer-macros [sel sel1]]
    [reagent.core :as reagent :refer [atom]]
    [reagent.dom :as rdom]
    [reagent.session :as session]
    [reitit.frontend :as reitit]
    [clerk.core :as clerk]
    [accountant.core :as accountant]
    [goog.dom :as gdom]
    [ludovico.player :as player]
    [ludovico.synth :as synth]
    [reagent-material-ui.core.input-label :refer [input-label]]
    [reagent-material-ui.core.menu-item :refer [menu-item]]
    [reagent-material-ui.core.form-control :refer [form-control]]
    [reagent-material-ui.core.select :refer [select]]
    [applied-science.js-interop :as j]
    )
  )

;(def midi-src "midi/fur_elise.mid")
(def midi-src "midi/toccata_and_fugue_in_d_minor.mid")
;(def midi-src "midi/song_for_my_father.mid")
;(def midi-src "midi/tetris.mid")
;(def midi-src "midi/nocturne_1.mid")

;; -------------------------
;; Routes

(def router
  (reitit/router
    [["/" :index]
     ["/songs"
      ["" :songs]
      ["/:song-id" :song]]
     ["/about" :about]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; -------------------------
;; Page components

(.addEventListener
  js/window
  "DOMContentLoaded"
  (fn [] (js/console.log @player/midi-player-atom))
  )

(defn on-midi-file-selected [input]
  (let
    [fr (js/FileReader.)
     files (j/get-in input [:target :files])
     file (first files)
     ]
    (j/assoc! fr :onload #(swap-vals! player/midi-player-atom assoc :midi-src (j/get fr :result)))
    (j/call fr :readAsDataURL file)
    )
  )

(defn home-page []
  (fn []
    [:span.main
     [:h1 "Ludovico"]
     ; https://material-ui.com/components/selects/
     [:div
      [:h5 {:class "section-label"} "Load Midi"]
      ; https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API
      [:audio#midi-track {:src (get @player/midi-player-atom :midi-src) :status "stopped"}]
      [:input {:type "file" :on-change on-midi-file-selected}]
      [:div
       [:button {:on-click #(player/on-play-btn-click)} [:span (get @player/midi-player-atom :next)]]
       [:button {:on-click #(player/on-stop-btn-click)} [:span "Stop"]]
       ]
      ]
     [:div [:button {:aria-checked "false" :on-click #((synth/play-midi-note-f 74 0.1))} [:span "Ping"]]]
     ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     [:div#sketch]
     ;[:ul [:li [:a {:href (path-for :songs)} "Songs list"]]]
     ]
    )
  )

(defn songs-page []
  (fn []
    [:span.main
     [:h1 "Songs"]
     [:ul (map (fn [song-id]
                 [:li {:name (str "song-" song-id) :key (str "song-" song-id)}
                  [:a {:href (path-for :song {:song-id song-id})} "Song: " song-id]])
               (range 1 60))]]))


(defn song-page []
  (fn []
    (let [routing-data (session/get :route)
          song (get-in routing-data [:route-params :song-id])]
      [:span.main
       [:h1 (str "Song " song "")]
       [:p [:a {:href (path-for :songs)} "Back to songs list"]]])))


(defn about-page []
  (fn [] [:span.main
          [:h1 "About"]]))


;; -------------------------
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :songs #'songs-page
    :song #'song-page))


;; -------------------------
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About"]]]
       [page]
       [:footer
        [:p "Ludovico was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; -------------------------
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (gdom/getElement "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
    {:nav-handler
     (fn [path]
       (let [match (reitit/match-by-path router path)
             current-page (:name (:data match))
             route-params (:path-params match)]
         (reagent/after-render clerk/after-render!)
         (session/put! :route {:current-page (page-for current-page)
                               :route-params route-params})
         (clerk/navigate-page! path)
         ))
     :path-exists?
     (fn [path]
       (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))
